name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: download dependencies 
        run: pip install -r requirements.txt

      - name: Log in to GHCR  
        uses: docker/login-action@v3
        with:
          registry: ghcr.io 
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}  

# TODO: Install dependencies and run tests
